#include "SandboxLayer.h"

#include <rlImGui.h>
#include <imgui.h>

SandboxLayer::SandboxLayer(Engine::Renderer* displayRenderer) : Engine::Layer("SandboxLayer"), m_DisplayRenderer(displayRenderer)
{
    // Constructor simply stores the renderer pointer.
}

void SandboxLayer::OnAttach()
{
    // Currently nothing to initialize when the layer attaches.
}

void SandboxLayer::OnDetach()
{
    // No special cleanup required for this layer.
}

void SandboxLayer::OnUpdate(float deltaTime)
{
    // Camera updates are handled by the renderer; begin a new render if requested.
    if (m_RequestRender && !m_Renderer.IsRendering())
    {
        m_Renderer.StartRender(m_Scene, m_DisplayRenderer->GetCamera());
        m_RequestRender = false;
    }
}


void SandboxLayer::OnImGuiRender()
{
    ImGui::Begin("Render Stats", nullptr);
    ImGui::Text("Render Time: %.2f ms", m_RenderTime);
    if (ImGui::Button("Render"))
    {
        m_RequestRender = true;
    }
    ImGui::End();
}

void SandboxLayer::OnSceneRender()
{
    if (m_Renderer.IsRendering())
    {
        // Render mode: display progressive framebuffer generated by the ray tracer.
        const Image& l_Image = m_Renderer.GetFrame();
        m_DisplayRenderer->RenderImage(static_cast<const Color*>(l_Image.data), l_Image.width, l_Image.height);
    }

    else
    {
        // Editor mode: show real-time preview using the renderer's camera.
        m_DisplayRenderer->Begin3D(m_DisplayRenderer->GetCamera());
        // Preview drawing could be added here in the future.
        m_DisplayRenderer->End3D();
    }

    // Blit whichever image the display renderer currently holds to the screen.
    const Texture2D& l_Texture = m_DisplayRenderer->GetFrameTexture();
    Rectangle l_Source{ 0.0f, 0.0f, static_cast<float>(l_Texture.width), static_cast<float>(-l_Texture.height) };
    DrawTextureRec(l_Texture, l_Source, Vector2{ 0.0f, 0.0f }, WHITE);

    // TODO: Support pause/resume and saving final image
}