#pragma once

#include "Renderer/CameraController.h"

#include <raylib.h>

#include <vector>
#include <thread>
#include <atomic>
#include <string>
#include <chrono>
#include <mutex>

namespace Engine
{
    class Scene; ///Forward declaration of the scene container used during ray tracing.

    /**
     *\brief Handles all drawing operations and provides a simple frame buffer interface.
     */
    struct RenderStep
    {
        std::string m_Name;       ///< Human readable name of the step.
        double m_ElapsedMs{ 0.0 };///< Time spent in this step in milliseconds.
    };

    class Renderer
    {
    public:
        /**\brief Rendering techniques supported by the engine.
         * Raster: traditional rasterization using the GPU graphics pipeline.
         * RayTrace: CPU based path for ray-traced rendering.
         * RayTraceGPU: GPU-accelerated tracing; requires ENGINE_ENABLE_GPU.
         * Future improvement: expand with hybrid modes to leverage modern hardwar
         */
        enum class RenderMode
        {
            Raster,        ///Conventional raster pipeline for real-time drawing.
            RayTrace,      ///CPU ray tracing path; enables high-quality effects.
            RayTraceGPU    ///GPU compute path; preferred for complex scenes when available.
        };

        /**\brief Select the active rendering technique.*/
        void SetRenderMode(RenderMode mode);
        /**\brief Retrieve the currently active rendering mode.*/
        RenderMode GetRenderMode() const;
        /**\brief Initialize renderer state and prepare for drawing using the window dimensions.*/
        bool Initialize(int width, int height);
        /**\brief Release resources allocated by the renderer.*/
        void Shutdown();

        /**\brief Start a new frame for 2D/3D rendering.*/
        void BeginFrame();
        /**\brief Finalize the current frame.*/
        void EndFrame();

        /**\brief Enter 3D drawing mode using the provided camera.*/
        void Begin3D(Camera3D camera);
        /**\brief Leave 3D drawing mode.*/
        void End3D();

        /**\brief Resize or recreate the internal frame texture. Returns false on allocation failure.*/
        bool ResizeFrameTexture(int width, int height);
        /**\brief Upload a color buffer into the frame texture. Optionally only update changed regions.*/
        void RenderImage(const Color* buffer, int width, int height);

        /**\brief Access the camera used for 3D rendering.*/
        const Camera& GetCamera() const;
        /**\brief Update the internal camera based on user input.*/
        void UpdateCamera(float deltaTime);
        /**\brief Retrieve the current frame texture.*/
        const Texture2D& GetFrameTexture() const;
        /**\brief Query the size in pixels of a single render tile.
         * Future improvement: support dynamic tile sizing strategies.
         */
        int GetTileSize() const;
        
        // --- CPU Ray tracing interface ---------------------------------------
        /**\brief Begin a ray-traced render of the given scene from the camera.*/
        void StartRender(const Scene& scene, const Camera& camera);
        /**\brief Request worker threads to stop and wait for completion.*/
        void StopRender();
        /**\brief Query whether a ray-traced render is currently running.*/
        bool IsRendering() const;
        /**\brief Access the CPU-side frame buffer generated by ray tracing.*/
        const Image& GetFrame() const;
        /**\brief Fraction of tiles completed by workers in [0,1].*/
        float GetProgress() const;
        /**\brief Retrieve a thread-safe snapshot of recorded render steps.*/
        std::vector<RenderStep> GetRenderSteps() const;

    private:
        CameraController m_CameraController{}; ///Centralized camera controller for input.
        RenderTexture2D m_RenderTexture = { 0 }; ///Render texture backing the frame buffer.
        RenderMode m_RenderMode = RenderMode::RayTraceGPU; ///Current rendering approach; includes GPU path when ENGINE_ENABLE_GPU.
        int m_FrameWidth = 0; ///Cached width of the frame texture.
        int m_FrameHeight = 0; ///Cached height of the frame texture.
        std::vector<Color> m_CachedPixels = { }; ///Copy of last uploaded pixel data.
        std::vector<Color> m_SubBuffer = { }; ///Reusable buffer for sub-region uploads to avoid frequent allocations.
        int m_TileSize = 16; ///Side length of each tile; TODO: explore adaptive tiling.

        // --- Ray tracing state -------------------------------------------------
        std::vector<std::jthread> m_Workers;             ///Background workers performing the trace. TODO: replace with GPU dispatch when available.
        std::atomic<bool> m_IsRendering{ false };        ///True while workers are active.
        std::atomic<bool> m_StopRequested{ false };      ///Signals workers to exit their loop.
        Image m_Framebuffer{};                           ///CPU side color buffer used for ray tracing output.

        const Scene* m_CurrentScene{ nullptr };          ///Scene being rendered.
        Camera m_CurrentCamera{};                        ///Copy of camera for consistent rays.

        std::atomic<int> m_NextTile{ 0 };                ///Index of the next tile to process.
        int m_TilesX{ 0 };                               ///Number of tiles horizontally.
        int m_TilesY{ 0 };                               ///Number of tiles vertically.
        int m_TotalTiles{ 0 };                           ///Total amount of tiles in the frame.
        std::atomic<int> m_TilesCompleted{ 0 };          ///Tiles completed by worker threads.

        std::vector<RenderStep> m_Steps;                 ///Chronological steps recorded during rendering.
        mutable std::mutex m_StepsMutex;                 ///Protects access to m_Steps for thread safety.
        std::chrono::high_resolution_clock::time_point m_RenderStart{}; ///<Absolute start time of the render.
        std::chrono::high_resolution_clock::time_point m_TileProcessingStart{}; ///<Start time for tile processing.
        double m_RenderDurationMs{ 0.0 };                ///Total duration of the last render in milliseconds.
        std::atomic<int> m_WorkersFinished{ 0 };         ///Number of workers that finished tracing.
        int m_MaxDepth{ 50 };                           ///Maximum recursion depth for ray tracing.
        ///TODO: expose via user configuration.

        int m_SamplesPerPixel{ 4 };                     ///Jittered rays per pixel for anti-aliasing.
        ///Higher values improve quality but slow rendering. Future improvement: stratified sampling.
        
        /**\brief Entry point for worker threads processing tiles.*/
        void WorkerThread(int threadID);

#ifdef ENGINE_ENABLE_GPU
        /**\brief Upload per-frame parameters and dispatch the GPU compute shader.
         * Future improvement: move parameter packing into a dedicated constant buffer structure.
         */
        void DispatchGPU(const Scene& scene, const Camera& camera);

        Shader m_GpuPipeline{ 0 }; ///< Compute shader pipeline used during RenderMode::RayTraceGPU.
        unsigned int m_NodeBuffer{ 0 };      ///< GPU buffer containing flattened BVH nodes.
        unsigned int m_PrimitiveBuffer{ 0 }; ///< GPU buffer containing scene primitives.
#endif
    };
}